# Generated by Django 4.1.1 on 2022-09-08 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category_id',
            new_name='category',
        ),
    ]
